# Generated by Django 6.0.5 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='spices/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
