# Generated by Django 6.0.5 on 2026-05-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner_image_file_spiceitem_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiceitem',
            name='brand_name',
            field=models.CharField(default='Lexvers', max_length=120),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='pack_size',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
