# Generated by Django 6.0.5 on 2026-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_homepagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('large', 'Large Hero'), ('compact', 'Small Photo Slider')], default='large', max_length=12),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='compact_hero_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='compact_hero_interval_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
