# Generated by Django 6.0.5 on 2026-05-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_banner_placement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiceItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(upload_to='spices/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.spiceitem')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
