# Generated by Django 6.0.5 on 2026-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_spiceitemphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=180)),
                ('store_name', models.CharField(max_length=150)),
                ('business_type', models.CharField(choices=[('individual', 'Individual Seller'), ('proprietor', 'Proprietorship'), ('partnership', 'Partnership'), ('company', 'Company / Pvt Ltd')], default='individual', max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=24)),
                ('bank_account_name', models.CharField(blank=True, max_length=140)),
                ('bank_account_number', models.CharField(blank=True, max_length=34)),
                ('bank_ifsc', models.CharField(blank=True, max_length=16)),
                ('business_address', models.TextField(blank=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='seller_docs/pan/')),
                ('gst_document', models.FileField(blank=True, null=True, upload_to='seller_docs/gst/')),
                ('bank_document', models.FileField(blank=True, null=True, upload_to='seller_docs/bank/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='seller_docs/address/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('admin_note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
