# Generated by Django 6.0.5 on 2026-05-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_initial_stock(apps, schema_editor):
    SpiceItem = apps.get_model('store', 'SpiceItem')

    SpiceItem.objects.filter(initial_stock=0).update(initial_stock=F('stock'))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_sellerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='owner_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller')], default='admin', max_length=12),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='return_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.sellerapplication'),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='shipping_weight',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='sku_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='sub_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='spiceitem',
            name='warranty_details',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_initial_stock, migrations.RunPython.noop),
    ]
