# Generated by Django 4.2.7 on 2026-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_orderitem_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=12),
        ),
    ]
