# Generated by Django 4.2.7 on 2026-06-03 07:22

from django.db import migrations


SELLER_EMAIL = 'sel@gmail.com'


def remove_seeded_demo_seller(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SellerApplication = apps.get_model('store', 'SellerApplication')

    SellerApplication.objects.filter(
        email=SELLER_EMAIL,
        name='Demo Seller',
        store_name='Lexvers Seller Store',
    ).delete()

    User.objects.filter(
        username=SELLER_EMAIL,
        email=SELLER_EMAIL,
        is_staff=False,
        is_superuser=False,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_coupon_courierpartner_notificationtemplate_offer_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_seeded_demo_seller, migrations.RunPython.noop),
    ]
