# Generated by Django 4.2.7 on 2026-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_seeded_demo_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
