# Generated by Django 6.0.5 on 2026-06-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_spiceitem_product_id_and_subcategory_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku_code', models.CharField(blank=True, max_length=80)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='spices/quantity_options/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_options', to='store.spiceitem')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'unique_together': {('product', 'label')},
            },
        ),
    ]
