# Generated by Django 4.2.7 on 2026-06-12 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_order_system(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    OrderItem = apps.get_model('store', 'OrderItem')
    OrderStatusHistory = apps.get_model('store', 'OrderStatusHistory')

    for index, order in enumerate(Order.objects.order_by('created_at', 'pk'), start=1):
        update_fields = []
        if not order.order_id:
            base_code = order.order_number or f'ORD-{order.created_at:%Y%m%d}-{index:04d}'
            candidate = base_code[:24]
            suffix = 1
            while Order.objects.exclude(pk=order.pk).filter(order_id=candidate).exists():
                suffix += 1
                candidate = f'{base_code[:19]}-{suffix}'[:24]
            order.order_id = candidate
            update_fields.append('order_id')

        if order.shipping_address:
            bits = [bit.strip() for bit in order.shipping_address.split(',') if bit.strip()]
            if not order.house and bits:
                order.house = bits[0][:180]
                update_fields.append('house')
            if not order.area and len(bits) > 1:
                order.area = bits[1][:180]
                update_fields.append('area')
            if not order.city and len(bits) > 2:
                order.city = bits[-2][:80]
                update_fields.append('city')
        if update_fields:
            order.save(update_fields=list(dict.fromkeys(update_fields)))

        OrderItem.objects.filter(order=order, item_status='pending').update(item_status=order.status)
        if not OrderStatusHistory.objects.filter(order=order).exists():
            OrderStatusHistory.objects.create(order=order, status=order.status, note='Backfilled existing order status')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_productquantityoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ordered', 'Ordered'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=12),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='area',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='India', max_length=80),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='house',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='India', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_seen_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_seen_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productquantityoption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery'), ('demo', 'Demo Payment')], default='cod', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_signature', models.CharField(blank=True, max_length=240)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('is_demo', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='store.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Placed'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.orderitem')),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('customer', 'Customer')], max_length=12)),
                ('notification_type', models.CharField(choices=[('new_order', 'New order received'), ('status_updated', 'Order status updated'), ('payment_updated', 'Payment updated')], default='new_order', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('is_read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.orderitem')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='store.sellerapplication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.spiceitem')),
                ('quantity_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='store.productquantityoption')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('cart', 'product', 'quantity_option')},
            },
        ),
        migrations.RunPython(backfill_order_system, migrations.RunPython.noop),
    ]
