# Generated by Django 6.0.5 on 2026-06-19 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cart_customeraddress_address_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='aadhaar_back',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/aadhaar_back/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='aadhaar_front',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/aadhaar_front/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='admin_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='approval_access_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='approx_products_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='branch_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='brand_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='business_proof',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/business_proofs/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='business_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/business_registration/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='cancelled_cheque',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/cancelled_cheques/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='confirm_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='gst_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='owner_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='owner_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='owner_photo',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/owner_photos/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/pan_cards/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_address_line1',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_address_line2',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_landmark',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_pincode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_same_as_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='primary_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='product_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/profile_photos/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='sells_handmade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='shop_photo',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/shop_photos/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='signature_upload',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/signatures/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/store_banners/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='store_display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/store_logos/'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='tax_pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual Seller'), ('proprietor', 'Proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('llp', 'LLP'), ('company', 'Company / Pvt Ltd')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More Info Required'), ('blocked', 'Blocked')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='SellerApplicationExtraDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='seller_docs/extra/')),
                ('original_name', models.CharField(blank=True, max_length=220)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_documents', to='store.sellerapplication')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
