# Generated by Django 4.2.7 on 2026-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sellerapplication_aadhaar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('seller_register', 'Seller registration'), ('customer_register', 'Customer registration'), ('login', 'Login'), ('forgot_password', 'Forgot password')], max_length=32)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used', 'expires_at'], name='store_email_email_890829_idx'), models.Index(fields=['created_at'], name='store_email_created_d10f8c_idx')],
            },
        ),
    ]
