# Generated by Django 6.0.5 on 2026-06-23 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def normalize_shipping_and_template_data(apps, schema_editor):
    ShipmentTracking = apps.get_model('store', 'ShipmentTracking')
    NotificationTemplate = apps.get_model('store', 'NotificationTemplate')

    def normalized_status(value):
        raw = (value or '').strip().lower().replace('-', ' ').replace('_', ' ')
        exact = {
            'pending': 'pending',
            'pending pickup': 'pending',
            'processing': 'pending',
            'packed': 'packed',
            'ready to ship': 'packed',
            'shipped': 'shipped',
            'in transit': 'shipped',
            'dispatched': 'shipped',
            'out for delivery': 'out_for_delivery',
            'delivered': 'delivered',
            'completed': 'delivered',
            'cancelled': 'cancelled',
            'canceled': 'cancelled',
        }
        if raw in exact:
            return exact[raw]
        if 'out' in raw and 'deliver' in raw:
            return 'out_for_delivery'
        if 'deliver' in raw:
            return 'delivered'
        if 'cancel' in raw:
            return 'cancelled'
        if 'ship' in raw or 'transit' in raw or 'dispatch' in raw:
            return 'shipped'
        if 'pack' in raw:
            return 'packed'
        return 'pending'

    for shipment in ShipmentTracking.objects.all().only('id', 'status'):
        new_status = normalized_status(shipment.status)
        if shipment.status != new_status:
            shipment.status = new_status
            shipment.save(update_fields=['status'])

    used_slugs = set()
    for template in NotificationTemplate.objects.all().only('id', 'name', 'slug'):
        base = slugify(template.slug or template.name) or f'template-{template.pk}'
        candidate = base
        suffix = 2
        while candidate in used_slugs:
            candidate = f'{base}-{suffix}'
            suffix += 1
        used_slugs.add(candidate)
        if template.slug != candidate:
            template.slug = candidate
            template.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller')], default='admin', max_length=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='store.sellerapplication'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courierpartner',
            name='api_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courierpartner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='courierpartner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='courierpartner',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='estimated_days',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='is_serviceable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='available_variables',
            field=models.CharField(blank=True, default='{{customer_name}}, {{order_id}}, {{seller_name}}, {{amount}}', max_length=240),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='purpose',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat Amount')], default='percent', max_length=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='flash_sales', to='store.spiceitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='store.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_status',
            field=models.CharField(default='Not scheduled', max_length=80),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='returns/proofs/'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='proof_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='admin_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shippingcharge',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingcharge',
            name='max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(normalize_shipping_and_template_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='store.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='store.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All users'), ('customers', 'All customers'), ('sellers', 'All sellers'), ('selected_customers', 'Selected customers'), ('selected_sellers', 'Selected sellers')], default='all', max_length=24)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('customers', models.ManyToManyField(blank=True, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
                ('sellers', models.ManyToManyField(blank=True, related_name='push_notifications', to='store.sellerapplication')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_id', models.CharField(blank=True, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account', models.CharField(blank=True, max_length=80)),
                ('upi_id', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('admin_note', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_payout_requests', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='store.sellerapplication')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='pending', max_length=16)),
                ('admin_note', models.CharField(blank=True, max_length=240)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.sellerapplication')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('admin_note', models.CharField(blank=True, max_length=240)),
                ('product_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='store.productreview')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('seller_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='store.sellerreview')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
