# Generated by Django 6.0.5 on 2026-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_adminimportantdocument_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplicationextradocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
